# Generated by Django 6.0.6 on 2026-06-24 03:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('points_reward_eligible', models.BooleanField(default=True, help_text='Can users earn points buying this?')),
                ('shopee_item_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('shipping_address', models.TextField()),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('points_discount_applied', models.DecimalField(decimal_places=2, default=0.0, help_text='Cash value deduction from points', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final amount after point discount calculations', max_digits=10)),
                ('points_redeemed_here', models.IntegerField(default=0)),
                ('points_earned_here', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Online Payment (GCash/Maya/Card)'), ('COD', 'Cash on Delivery (COD)')], default='ONLINE', max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending Payment / Verification'), ('PAID', 'Paid / Ready for Packaging'), ('SHIPPED', 'Handed over to Courier'), ('DELIVERED', 'Delivered & Completed'), ('CANCELLED', 'Cancelled'), ('RTS', 'Return to Sender')], default='PENDING', max_length=20)),
                ('courier_partner', models.CharField(blank=True, choices=[('JT', 'J&T Express'), ('FLASH', 'Flash Express'), ('LBC', 'LBC Express'), ('LALAMOVE', 'Lalamove')], max_length=15, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('awb_pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='dashboard.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Format: 09XXXXXXXXX', max_length=20)),
                ('default_shipping_address', models.TextField(blank=True, null=True)),
                ('loyalty_points', models.IntegerField(default=0, help_text='Available reward points balance', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Points Earned from Purchase'), ('REDEEMED', 'Points Redeemed on Checkout'), ('REFUNDED', 'Points Returned from Cancellation'), ('ADJUSTED', 'Manual Admin Adjustment')], max_length=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to='dashboard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='dashboard.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
